name: "job: Build and test"
description: 'Composite build & test action'

inputs:
    node-version:
        description: Node.js version
        required: true

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@master
        - uses: ./.github/actions/build
          with:
              node-version: ${{ inputs.node-version }}
        - uses: ./.github/actions/test
          with:
              node-version: ${{ inputs.node-version }}
