name: "Action: Analyze"
description: 'Composite analyze action'

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@master

        - uses: actions/setup-node@master
          with:
              cache: 'yarn'
        - shell: sh
          run: yarn install --frozen-lockfile
        - uses: actions/cache@master
          id: restore-build
          with:
              path: ./*
              key: ${{ github.sha }}

        - name: Lint
          shell: sh
          run: yarn lint

        - name: CodeQL
          uses: github/codeql-action/init@v2
          with:
              languages: 'javascript'
        - uses: github/codeql-action/autobuild@v2
        - uses: github/codeql-action/analyze@v2

        - name: Coveralls
          uses: coverallsapp/github-action@1.1.3
