name: "Action: Deploy Storybook"
description: 'Composite storybook deploy action'

inputs:
    branch:
        description: branch name
        required: false
        default: main

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-node@v3
          with:
              node-version: ${{ inputs.node-version }}
              cache: 'yarn'

        - name: Install dependencies
          shell: sh
          run: yarn --frozen-lockfile

        - name: Build Storybook
          shell: sh
          run: yarn build-storybook --output-dir storybook-static/${{ inputs.branch }}

        - name: Publish Storybook
          uses: JamesIves/github-pages-deploy-action@v4
          with:
              FOLDER: storybook-static
