name: Build

on:
    workflow_call:
        inputs:
            node-version:
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Use Node.js ${{ inputs.node-version }}
              uses: actions/setup-node@master
              with:
                  node-version: ${{ inputs.node-version }}
                  cache: 'yarn'
            - run: yarn --frozen-lockfile
            - run: yarn build
            - run: yarn lint
            - run: yarn test
