name: "reusable flow: Build and test"

on:
    workflow_call:
        inputs:
            node-version:
                required: true
                type: string

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - uses: ./.github/actions/build
              with:
                  node-version: ${{ inputs.node-version }}

    lint-test:
        name: Lint & Test
        runs-on: ubuntu-latest
        needs: [build]

        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/test
              with:
                  node-version: ${{ inputs.node-version }}
