name: Bump

on:
    workflow_call:
        inputs:
            githubToken:
                required: true
                type: string

jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Automated Version Bump
              uses: phips28/gh-action-bump-version@master
              env:
                GITHUB_TOKEN: ${{ inputs.githubToken }}
              with:
                  major-wording: 'MAJOR'
                  minor-wording: 'MINOR'
                  patch-wording: 'PATCH,FIX'
                  rc-wording: 'ALPHA,BETA'
