name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
    build-test:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [16.13.2]
        name: Node.js ${{ matrix.node }} @ ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@master

            - uses: ./.github/actions/build
              with:
                  node-version: ${{ matrix.node }}

            - uses: ./.github/actions/test
              with:
                  node-version: ${{ matrix.node }}
                  with-coverage: true

    analyze:
        needs: build-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/analyze
