name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/build
              with:
                  node-version: 16.x

    lint-test:
        name: Lint & Test
        runs-on: ubuntu-latest
        needs: [build]

        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/test
              with:
                  node-version: 16.x
