name: Push to Master

on:
    push:
        branches: [ master ]

env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
    build:
        name: Node.js 16
        uses: ./.github/workflows/build-test.yml
        with:
            node-version: 16.13.2
    release:
        needs: build
        name: Bump & Release
        uses: ./.github/workflows/release.yml
        with:
            node-version: 16.13.2
        secrets:
            githubToken: ${{ github.token }}
            npmToken: ${{ secrets.NPM_TOKEN }}
    publish-storybook:
        needs: build
        name: Publish Storybook
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/storybook
              with:
                branch: master
    build-legacy:
        name: Node.js 14
        uses: ./.github/workflows/build-test.yml
        with:
            node-version: 14.x

