name: Push to Master

on:
    push:
        branches: [ master ]
    workflow_run:
        inputs:
            node-version:
                type: string
                required: false
                default: 16.13.2
            node-legacy-version:
                type: string
                required: false
                default: 14.x
    workflow_dispatch:
        inputs:
            node-version:
                type: string
                required: false
                description: nodejs version
                default: 16.13.2
            node-legacy-version:
                type: string
                required: false
                description: nodejs legacy version
                default: 14.x

jobs:
    build:
        name: Node.js ${{ inputs.node-version }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/build
              with:
                  node-version: ${{ inputs.node-version }}

    lint-test:
        name: Lint & Test
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/test
              with:
                  node-version: ${{ inputs.node-version }}

    release:
        needs: lint-test
        name: Bump & Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/release
              with:
                node-version: ${{ inputs.node-version }}
                githubToken: ${{ github.token }}
                npmToken: ${{ secrets.NPM_TOKEN }}

    publish-storybook:
        needs: lint-test
        name: Publish Storybook
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/storybook
              with:
                branch: master

    build-legacy:
        name: Node.js ${{ inputs.node-legacy-version }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/build
              with:
                node-version: ${{ inputs.node-legacy-version }}

    lint-test-legacy:
        name: Lint & Test
        runs-on: ubuntu-latest
        needs: build-legacy
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/test
              with:
                  node-version: ${{ inputs.node-legacy-version }}
