name: Push to Master

on:
    push:
        branches: [ master ]

jobs:
    build:
        name: Node.js 16
        uses: ./.github/workflows/build-test.yml
        with:
            node-version: 16.13.2
    release:
        needs: build
        name: Bump & Release
        uses: ./.github/workflows/release.yml
        with:
            node-version: 16.13.2
        secrets:
            githubToken: ${{ github.token }}
            npmToken: ${{ secrets.NPM_TOKEN }}
    publish-storybook:
        needs: build
        name: Publish Storybook on Github Pages
        uses: ./.github/workflows/storybook.yml
        with:
            branch: master
            githubActor: ${{ github.actor }}
          secrets:
            githubToken: ${{ github.token }}
    build-legacy:
        name: Node.js 14
        uses: ./.github/workflows/build-test.yml
        with:
            node-version: 14.x

