name: Push to Master

on:
    push:
        branches: [ master ]

jobs:
    build-test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node: [14, 16.13.2]
        name: Node.js ${{ matrix.node }} @ ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/build
              with:
                node-version: ${{ matrix.node }}
            - uses: ./.github/actions/test
              with:
                node-version: ${{ matrix.node }}
                with-coverage: true

    analyze:
        needs: build-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/analyze

    release:
        needs: analyze
        name: Bump & Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/release
              with:
                node-version: 16.13.2
                githubToken: ${{ github.token }}
                npmToken: ${{ secrets.NPM_TOKEN }}

    publish-storybook:
        needs: analyze
        name: Publish Storybook
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/storybook
              with:
                branch: master
