name: Push to Master

on:
    push:
        branches: [ master ]
    workflow_call:
        inputs:
            node-version:
                type: string
                required: false
                default: 16.13.2
            node-major-version:
                type: string
                required: false
                default: 16
            node-legacy-version:
                type: string
                required: false
                default: 14.x

jobs:
    build:
        name: Node.js ${{ node-major-version }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/build
              with:
                  node-version: ${{ node-version }}

    lint-test:
        name: Lint & Test
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/test
              with:
                  node-version: ${{ node-version }}

    release:
        needs: build
        name: Bump & Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/release
              with:
                node-version: ${{ node-version }}
                githubToken: ${{ github.token }}
                npmToken: ${{ secrets.NPM_TOKEN }}

    publish-storybook:
        needs: build
        name: Publish Storybook
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/storybook
              with:
                branch: master

    build-legacy:
        name: Node.js 14
        uses: ./.github/workflows/build-test.yml
        with:
            node-version: ${{ node-legacy-version }}
