name: Push to Master

on:
    push:
        branches: [ master ]

jobs:
    build:
        name: Build on latest Node.js
        uses: ./.github/workflows/build.yml
        with:
            node-version: 16.x
    bump:
        needs: build
        name: Bump version
        uses: ./.github/workflows/bump.yml
        with:
            githubToken: ${{ github.token }}
    build-legacy:
        name: Build on legacy Node.js
        uses: ./.github/workflows/build.yml
        with:
            node-version: 14.x
