name: Push to Master

on:
    push:
        branches: [ master ]
    workflow_dispatch:
        inputs:
            node-version:
                description: Node.js version
                required: false
                default: 16.13.2
            node-legacy-version:
                description: Node.js legacy version
                required: false
                default: 14.x
jobs:
    build-test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node:
                    - "${{ github.event.inputs.node-version }}"
                    - "${{ github.event.inputs.node-legacy-version }}"
        name: Node.js ${{ matrix.node }} @ ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/build-test
              with:
                  node-version: ${{ matrix.node }}

    release:
        needs: build-test
        name: Bump & Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/release
              with:
                node-version: 16.13.2
                githubToken: ${{ github.token }}
                npmToken: ${{ secrets.NPM_TOKEN }}

    publish-storybook:
        needs: build-test
        name: Publish Storybook
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/storybook
              with:
                branch: master
