name: "reusable flow: Release"

on:
    workflow_call:
        inputs:
            node-version:
                type: string
                required: true
        secrets:
            githubToken:
                required: true
            npmToken:
                required: true

jobs:
    bump:
        runs-on: ubuntu-latest
        env:
            CI: true
            GITHUB_TOKEN: ${{ secrets.githubToken }}
            NPM_TOKEN: ${{ secrets.npmToken }}
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Version bump
              uses: phips28/gh-action-bump-version@master
              with:
                major-wording: 'MAJOR,BREAKING CHANGE'
                minor-wording: 'MINOR,FEAT,CHORE'
                rc-wording: 'ALPHA,BETA'

            - id: build
              uses: ./.github/workflows/build
              with:
                node-version: ${{ inputs.node-version }}

            - uses: actions/cache@master
              id: restore-build
              with:
                  path: ./*
                  key: ${{ github.sha }}

            - name: Publish to NPM
              run: |
                yarn copy
                echo "//registry.npmjs.org/:_authToken=${{ secrets.npmToken }} >> ./.npmrc"
                npm publish lib/ --access public
