name: "reusable flow: Release"

on:
    workflow_call:
        inputs:
            node-version:
                type: string
                required: true
        secrets:
            githubToken:
                required: true
            npmToken:
                required: true


jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Version bump
              uses: phips28/gh-action-bump-version@master
              env:
                GITHUB_TOKEN: ${{ secrets.githubToken }}
              with:
                major-wording: 'MAJOR,BREAKING CHANGE'
                minor-wording: 'MINOR,FEAT,CHORE'
                rc-wording: 'ALPHA,BETA'

            - id: build
              uses: ./.github/workflows/build
              with:
                node-version: ${{ inputs.node-version }}

            - uses: actions/cache@master
              id: restore-build
              with:
                  path: ./*
                  key: ${{ github.sha }}

            - name: Publish to NPM
              env:
                CI: true
                NPM_TOKEN: ${{ secrets.npmToken }}
              run: yarn release
