name: "reusable flow: Release"

on:
    workflow_call:
        secrets:
            githubToken:
                required: true
            npmToken:
                required: true


jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Version Bump and Release
              uses: mikeal/merge-release@master
              env:
                GITHUB_TOKEN: ${{ secrets.githubToken }}
                NPM_AUTH_TOKEN: ${{ secrets.npmToken }}
