name: "reusable flow: Release"

on:
    workflow_call:
        inputs:
            githubToken:
                required: true
                type: string
            npmToken:
                required: true
                type: string


jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Version Bump and Release
              uses: mikeal/merge-release@master
              env:
                GITHUB_TOKEN: ${{ inputs.githubToken }}
                NPM_AUTH_TOKEN: ${{ inputs.npmToken }}
