name: "reusable flow: Release"

on:
    workflow_call:
        secrets:
            githubToken:
                required: true
            npmToken:
                required: true


jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Version bump
              uses: phips28/gh-action-bump-version@master
              env:
                GITHUB_TOKEN: ${{ secrets.githubToken }}
              with:
                major-wording: 'MAJOR,BREAKING CHANGE'
                minor-wording: 'MINOR,FEAT,CHORE'
                rc-wording: 'ALPHA,BETA'

            - name: Publish to NPM
              uses: JS-DevTools/npm-publish@master
              env:
                CI: true
              with:
                token: ${{ secrets.npmToken }}
