name: "reusable flow: Deploy Storybook"

on:
    workflow_call:
        inputs:
            branch:
                type: string
                required: false
                default: master
        secrets:
            githubActor:
                required: true
            githubToken:
                required: true

jobs:
    build-storybook:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                node-version: ${{ inputs.node-version }}
                cache: 'yarn'
            - name: Install dependencies
              run: yarn --frozen-lockfile
            - name: Build Storybook
              run: yarn build-storybook --output-dir storybook-static/${{ inputs.branch }}
#              run: yarn storybook-to-ghpages --source-branch ${{ inputs.branch }} --out ${{ inputs.branch }} --ci
#              env:
#                GH_TOKEN: ${{ secrets.githubActor }}:${{ secrets.githubToken }}
            - name: Publish Storybook
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                GITHUB_TOKEN: ${{ secrets.githubToken }}
                FOLDER: storybook-static
